In [1]:
from skmultilearn.adapt import MLkNN
import numpy as np

In [2]:
num_samples = 10
num_labels = 5
X = np.random.rand(num_samples, 10)
y = np.random.choice([True, False], size=(num_samples, num_labels)).astype(float) # convert to float to support nans

In [3]:
nan_r = np.random.choice(range(num_samples), size=3)
nan_c = np.random.choice(range(num_labels), size=3)
nan_r, nan_c

(array([3, 3, 5]), array([4, 4, 3]))

In [4]:
for idx in zip(nan_r, nan_c):
    y[idx] = np.nan
y

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  1.,  0., nan],
       [ 1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1., nan,  1.],
       [ 1.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  1.,  1.]])

In [5]:
model = MLkNN(k=3)
model.fit(X, y)

MLkNN(k=3)

In [6]:
model.predict(X).todense().astype(bool)

matrix([[False,  True, False,  True,  True],
        [ True, False, False, False, False],
        [ True,  True, False,  True,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False, False],
        [False,  True, False,  True,  True],
        [ True,  True, False,  True, False],
        [False, False, False,  True,  True],
        [False,  True, False,  True,  True],
        [ True,  True, False,  True,  True]])

In [7]:
model.predict_proba(X).todense()

matrix([[0.45901639, 0.66666667, 0.44      , 0.78609626, 0.83050847],
        [0.89908257, 0.16666667, 0.44      , 0.44954128, 0.23444976],
        [0.89908257, 0.75      , 0.1641791 , 0.78609626, 0.83050847],
        [0.89908257, 0.16666667, 0.34375   , 0.44954128, 0.5505618 ],
        [0.89908257, 0.16666667, 0.1641791 , 0.44954128, 0.23444976],
        [0.45901639, 0.66666667, 0.44      , 0.78609626, 0.83050847],
        [0.89908257, 0.66666667, 0.34375   , 0.78609626, 0.23444976],
        [0.38888889, 0.16666667, 0.34375   , 0.78609626, 0.83050847],
        [0.45901639, 0.66666667, 0.44      , 0.78609626, 0.83050847],
        [0.89908257, 0.75      , 0.1641791 , 0.78609626, 0.83050847]])